### ISSUE TITLE
LA12 Crashed on 018B00055N - did not produce excel file

### ISSUE THREAD

**Issue by allen-cantrell** [danciucu/Xtractor#1]

**Comment by danciucu** [comment]
Solved for that particular file. Please let me know if there are more issues related to this. Currently the condition to eliminate false elements is this one:

`if len(strings[first_digit:last_digit + 1]) > 1 and len(strings) > 35 and first_digit < 6 and "/20" in strings:`

What this line does, is checking if the number identified is larger than one digit, if the total length of the "sentence" is longer than 35 characters, if the first digit is within the first 5 characters of the "sentence" and if "/20" string is inside the "sentence".

**Comment by allen-cantrell** [comment]
Could check to see if the number equals an actual element number designation?

**Comment by danciucu** [comment]
Sure, but there would be a problem with that condition - when the element number will change, that will imply a significant amount of work to update the script. I like to find conditions that are valid for all current reports.

**Comment by allen-cantrell** [comment]
Element numbers will not be changing.

**Comment by danciucu** [comment]
Okay, I will implement that!

**Comment by allen-cantrell** [comment]
Complete list of elements should be available on the Reference tab of the Field Notes spreadsheet.
